from .company_report import BisnodeCompanyReportTests
from .board_member_report import BisnodeBoardMemberReportTests
from .financial_statement_report import BisnodeFinancialStatementReportTests
from .historical_rating_report import BisnodeHistoricalRatingReportTests
